name: deploy to firebase hosting
on:
  push:
    branches:
      - main

jobs:
  deploy_web:
    name: Deploy game to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: unitythreedgame
